### ISSUE TITLE
Tutorial Proposal: Implement KNN using numpy.

### ISSUE THREAD

**Issue by bhavukkalra** [numpy/numpy-tutorials#133]
**Proposal**

This tutorial will cover a specific use case i.e **Implementing KNN using NumPy.** 
(KNN - K Nearest Neighbours)

**What will be covered in the Tutorial?**
- KNN Implementation 
- Euclidean distance implementation
- Tackling a standard classification problem

**Problem statement used for the Tutorial**

Given four data points for categories Fruit, Protein and Vegetable. 
Out of these given categories, Find out in which of these the fifth input, test data point lies.

Sample Attached Jupyter Notebook - [KNN Implementation](https://github.com/bhavukkalra/Genetic_Algorithms/blob/main/AI_assign2/KNN.ipynb)

**Comment by melissawm** [comment]
Hi @bhavukkalra  - thanks for the proposal!

One thing to note it that our documentation tends to follow (loosely, sometimes) the philosophy of the [Diátaxis framework](https://diataxis.fr) which includes the distinction between tutorials (meant for less experienced users, focused on teaching and best practices, as well as foundational concepts and ideas) and how-to guides (quick and direct guides for completing specific tasks).

If your idea is to build a tutorial, that would fit in this repo. If you are planning to write a how-to guide, that would go in the main repo. Because a KNN is a very specific application and not something that you would do from scratch necessarily, I don't think it should be a how-to, but rather a tutorial.

What do you think?

**Comment by bhavukkalra** [comment]
Correct, I might have missed on the terminologies and the subtle difference between a How to and Tutorial. My Intention is of creating a Tutorial only.

Edited the Initial Issue comment to also reflect it.

**Comment by rossbar** [comment]
My general sense is that KNN is a better fit for scikit-learn, which indeed has [extensive examples](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn-neighbors-kneighborsclassifier) demonstrating use-cases and the underlying implementation.

Just my two cents though - if there's strong motivation to put something together that really focuses on numpy features then by all means feel free to do so!

Since this has been stale for ~1 year, I will go ahead and close it. Feel free to reopen or submit PRs!
