### ISSUE TITLE
Set up gitpod

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy-tutorials#18]
After the final format for the repo is decided and merged.

**Comment by melissawm** [comment]
See the discussion in #20 . 

GitHub Codespaces is in beta, and that seems exactly like gitpod, so I might put this off for a while and see if codespaces solves our problem. If it does it's probably better to have a first-party application instead of a third-party one. I'll leave this issue open so we can reevaluate if necessary.

**Comment by InessaPawson** [comment]
@melissawm Now that we have access to Codespaces, shall we give it another go ?

**Comment by rossbar** [comment]
One of the main questions from me re: gitpod/codespaces is what is the end-goal of having a development environment for the `numpy-tutorials` repo? If it's to interactively edit the notebooks themselves, I think users would be better off using binder/jupyterhub, since those services are better suited for this use-case. If the end-goal is to make it easier for users to contribute their notebooks, then gitpod/codespaces might be a better fit - but even then there are steps that require "manual" intervention (e.g. converting to text-based notebook formats) that aren't solved by environment setup alone.

My sense is that environment setup is less likely to be a bottleneck than some of the other contribution steps. I think most users are pretty comfortable authoring/editing notebooks in the browser, and are less likely to be comfortable/familiar with the sphinx workflow for generating the site. However; if anyone has a sense that a cloud-based dev env would be useful for some subset of users I'm happy to give it a shot!

**Comment by bsipocz** [comment]
I'm with Ross on this topic and think that gitpod/codespaces are not really that useful for editing the content for the tutorials, and users of the tutorials are also better off with binder/colab/etc.

Can we close the issue?

**Comment by rossbar** [comment]
I'll go ahead and close this given the above discussion. If anyone wants to continue the discussion please feel free to reopen!
