### ISSUE TITLE
ENH: Add author tag to notebooks

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy-tutorials#57]
As @8bitmp3 points out [here](https://github.com/numpy/numpy-tutorials/pull/31#issuecomment-750326471), we don't currently have anything indicating the original authorship in the notebooks. We should add this and make sure it's retroactively applied to all the existing tutorials.

**Comment by melissawm** [comment]
After discussion today in our Documentation team meeting, here's where we are on this:

- It is helpful to think about attribution here, since even though this is part of an open source project and ownership of any generated work is ultimately given to the community, for large narrative documents it may make sense to give contributors some recognition of the work they are doing.
- The main issue is that when the Jupyter tutorials created before we decided on the workflow for the repo were converted to markdown, the history for those documents was effectively rewritten, causing the original authors to not be correctly linked to the final document. This, as far as I understand, won't be an issue for new documents because they will be converted during the PR stage and the authors can keep their commits when the PR is merged.
- If it were possible to recover this history so that the authors are correctly linked to their work, this would be sufficient.
- If this is not technically possible, we discussed maybe adding a line to documents similar to what is done [by PyTorch](https://pytorch.org/tutorials/beginner/nn_tutorial.html) listing the main author and maybe other contributors that make significant changes to the document. 

Further discussion is needed in any case. In the first case, the practical aspects have to be decided on, and in the second case, we should probably limit the amount of contributors listed as authors in any single document, and figure out the policy for that (e.g. are reviewers listed as authors, too?)

We agreed on continuing the discussion here, any suggestions or comments are welcome.

**Comment by melissawm** [comment]
Related discussion: https://github.com/numpy/numpy-tutorials/pull/31#issuecomment-750462841

**Comment by cooperrc** [comment]
@8bitmp3 brought up a great point on "who do I contact?" For clarification or suggestions. 

It looks like as we migrate to the next round of submissions the authorship is preserved. In this way, a user can look at the commit history and find authors/editors that can help. 

@rgommers pointed to allcontributors.org as a means to give credit with a bot. Looks nice.

**Comment by melissawm** [comment]
Hi folks, 

Pending further suggestions, I would like to propose that we solve this in the simplest possible way, which is asking the authors to do a trivial commit so they show up in `git blame` as authors of this final commit for each tutorial file. In that case, it will be clear to readers who to contact about it, and we don't risk potential future troubles with author bylines or attribution. If you accept this proposal, I'll remove the current attributions listed in the README (except for the external CS231 tutorial, which should still be properly attributed). For future tutorials, we can do a different process, keeping the authors commits throughout the whole review process. 

Let me know what you all think.

**Comment by melissawm** [comment]
I am closing this as it seems we have found a solution - please reopen if you think we still need to discuss this further.
